# drosera.toml
trap_name = "Drosera Liquidation Manipulation Trap"
path = "out/FlashBait.sol/FlashBait.json"
address = "0xDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEF" # optional placeholder
response_contract = "0xBA1BA1BA1BA1BA1BA1BA1BA1BA1BA1BA1BA1BA1"
response_function = "executeBytes(bytes)"

[metadata]
description = "Detects suspicious liquidation-manipulation patterns and logs them on-chain via executeBytes(bytes)."

[manifest]
# detection rules (informational; actual operator code implements heuristics)
detection_rule_1 = "txToLendingPool"
detection_rule_2 = "largeBorrowAndSwap"